### ISSUE TITLE
Enemies have elemental alignment of portal

### ISSUE THREAD

**Issue by dorhananel** [kdoffor1k/The-Archaic-Tower#15]
# Story/Task Details

- [x] Task 1: Enemies have visual indicator to their elemental alignment
- [x] Task 2: enemies elemental alignment is the same as the portal they were spawned from

# Acceptance Scenarios

- Given: a player is in a level
- When: an enemy is spawned from a protal
- Then: The enemy will receive the elemental alignment of the protal

#  Done Done
An enemies elemental alignment doesn't change after they spawned

**Comment by dwilliams326** [comment]
Finished but need to change the way alignment is checked.
