### ISSUE TITLE
practice range

### ISSUE THREAD

**Issue by dorhananel** [kdoffor1k/The-Archaic-Tower#3]
# Details

- [x] player can use the menu to go to the practice range
- [x] you can cast spells in the practice range
- [x] the practice range is an open area

## Acceptance Scenarios 

- Player can move between the main level and the practice range in both directions
- spells can be casted
- no limits in the practice range

## Done Done Criteria
a practice rang only menu tells you the statistics of the spell you just cast (damage, volume, area of effect, dps, cast time, speed)

**Comment by dwilliams326** [comment]
Menu transition works but needs a button for the actual transition
